require("image").setup({
	backend = "sixel",
	processor = "magick_rock",
	integrations = {
		markdown = {
			enabled = true,
			download_remote_images = true,
		},
	},
	max_width_window_percentage = 50,
	max_height_window_percentage = 40,
})

-- TODO make this better
require("claudecode").setup()
vim.keymap.set("n", "<space>cc", "<cmd>ClaudeCode<CR>", { noremap = true, desc = "Toggle Claude Code" })
vim.keymap.set("v", "<space>cc", "<cmd>ClaudeCode<CR>", { noremap = true, desc = "Claude Code with selection" })
vim.keymap.set("n", "<space>cf", "<cmd>ClaudeCodeFocus<CR>", { noremap = true, desc = "Toggle Claude Code Focus" })
vim.keymap.set("n", "<space>ca", "<cmd>ClaudeCodeDiffAccept<CR>", { noremap = true, desc = "Accept Claude diff" })
vim.keymap.set("n", "<space>cr", "<cmd>ClaudeCodeDiffDeny<CR>", { noremap = true, desc = "Reject Claude diff" })

-- matugen.lua is generated by noctalia into ~/.local/share/nvim/site/lua/
local ok, matugen = pcall(require, "matugen")
if ok then
	matugen.setup()
else
	require("catppuccin").setup({
		flavour = "mocha",
	})
	vim.cmd.colorscheme("catppuccin-mocha")
end

require("scrollbar").setup()

require("nvim-highlight-colors").setup({
	render = "background",
	enable_named_colors = false,
	enable_tailwind = false,
})

require("oil-git-status").setup()

local glance = require("glance")
local actions = glance.actions
glance.setup({
	mappings = {
		list = {
			["<M-j>"] = actions.next,
			["<M-k>"] = actions.previous,
		},
		preview = {
			["<M-j>"] = actions.next,
			["<M-k>"] = actions.previous,
		},
	},
})

vim.api.nvim_create_autocmd("LspAttach", {
	callback = function(args)
		local buf = args.buf
		local bopts = { buffer = buf, silent = true }
		vim.keymap.set("n", "<space>gr", "<cmd>Glance references<CR>", bopts)
		vim.keymap.set("n", "<space>gd", "<cmd>Glance definitions<CR>", bopts)
		vim.keymap.set("n", "<space>gi", "<cmd>Glance implementations<CR>", bopts)
		vim.keymap.set("n", "<space>gt", "<cmd>Glance type_definitions<CR>", bopts)
	end,
})

-- ts-context-commentstring: override commentstring via filetype.get_option
vim.schedule(function()
	local get_option = vim.filetype.get_option
	vim.filetype.get_option = function(filetype, option)
		return option == "commentstring" and require("ts_context_commentstring.internal").calculate_commentstring()
			or get_option(filetype, option)
	end
end)

vim.lsp.config("tsgo", {
	filetypes = { "typescript", "javascript", "typescriptreact", "javascriptreact", "html" },
})
vim.lsp.enable("tsgo")

vim.lsp.config("ruby_lsp", {
	cmd = { "rbenv", "exec", "ruby-lsp" },
	filetypes = { "ruby", "eruby" },
})
vim.lsp.enable("ruby_lsp")

vim.api.nvim_create_autocmd("TextYankPost", {
	group = vim.api.nvim_create_augroup("kickstart-highlight-yank", { clear = true }),
	callback = function()
		vim.highlight.on_yank()
	end,
})

vim.api.nvim_create_autocmd({ "InsertLeave", "TextChanged", "FocusLost", "BufLeave" }, {
	pattern = "*",
	callback = function()
		if vim.bo.modified and vim.bo.buftype == "" then
			vim.cmd("silent noautocmd write")
		end
	end,
})

vim.api.nvim_create_user_command("CharWordCount", function(opts)
	local start_line, end_line
	if opts.range == 0 then
		start_line = 0
		end_line = -1
	else
		start_line = opts.line1 - 1
		end_line = opts.line2
	end
	local lines = vim.api.nvim_buf_get_lines(0, start_line, end_line, true)
	local text = table.concat(lines, "\n")
	local words = 0
	for _ in text:gmatch("%S+") do
		words = words + 1
	end
	local chars = vim.fn.strchars(text)
	print(string.format("%d words · %d chars", words, chars))
end, { range = true })

local signal = vim.uv.new_signal()
signal:start("sigusr1", function()
	vim.schedule(function()
		package.loaded["matugen"] = nil
		local ok2, mat = pcall(require, "matugen")
		if ok2 then
			mat.setup()
		end
	end)
end)
